refactor: Update PR Preview Deployment workflow to fix port availability check logic and use unique ID for cleanup and redeployment

diff --git a/.github/workflows/pr-preview.yml b/.github/workflows/pr-preview.yml
--- a/.github/workflows/pr-preview.yml
+++ b/.github/workflows/pr-preview.yml
@@ -133,22 +133,29 @@ jobs:
           PROJECT=${{ matrix.project }}
           CLEAN_FLAG=${{ needs.comment_actions.outputs.clean_flag }}
           echo "Starting deployment for PR #$PR_NUMBER - Project: $PROJECT"
-          
-            # Find the first available port starting from 8000
-            START_PORT=8000
-            MAX_PORT=10000
-            PORT=$START_PORT
-            while [ $PORT -lt $MAX_PORT ]; do
-              if ! ss -tlnp | grep ":${PORT} " > /dev/null; then
-                break
-              fi
-              PORT=$((PORT + 1))
-            done
-            if [ $PORT -ge $MAX_PORT ]; then
-              echo "ERROR: No available ports found."
-              rm -f "$LOCK_FILE"
-              exit 1
+
+          # Find the first available port starting from 8000
+          START_PORT=8000
+          MAX_PORT=1000000
+          PORT=$START_PORT
+          echo "Checking for available ports..."
+          echo "start port: $PORT"
+          echo "max port: $MAX_PORT"
+          while [ $PORT -lt $MAX_PORT ]; do
+          echo "Checking port $PORT"
+            if ! ss -tlnp | grep ":${PORT} " > /dev/null; then
+              break
             fi
+            PORT=$((PORT + 1))
+          done
+
+          if [ $PORT -ge $MAX_PORT ]; then
+            echo "ERROR: No available ports found."
+            rm -f "$LOCK_FILE"
+            exit 1
+          else
+            echo "Available port found: $PORT"
+          fi
 
           UNIQUE_ID="${PROJECT}-${PR_NUMBER}-$PORT"
 
