refactor: reorganize preview deployment workflow for improved clarity and efficiency

diff --git a/.github/workflows/preview-deploy.yml b/.github/workflows/preview-deploy.yml
--- a/.github/workflows/preview-deploy.yml
+++ b/.github/workflows/preview-deploy.yml
@@ -77,29 +77,6 @@ jobs:
           PORT=$((PORT_RANGE_START + (PR_NUMBER + PROJECT_OFFSET) % PORT_RANGE))
           echo "port=$PORT" >> $GITHUB_OUTPUT
 
-      - name: Setup build environment
-        run: |
-          mkdir -p ./${{ matrix.project }}
-
-      - name: Use Node.js 20
-        uses: actions/setup-node@v4
-        with:
-          node-version: "20"
-
-      - name: Cache dependencies and build artifacts
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.npm
-            ${{ github.workspace }}/${{ matrix.project }}/.next/cache
-          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
-          restore-keys: |
-            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
-
-      - name: Install dependencies
-        working-directory: ./${{ matrix.project }}
-        run: npm i
-
       - name: Create or Update Initial Status Comments
         continue-on-error: true
         uses: actions/github-script@v6
@@ -154,6 +131,29 @@ jobs:
               });
             }
 
+      - name: Use Node.js 20
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+
+      - name: Setup build environment
+        run: |
+          mkdir -p ./${{ matrix.project }}
+
+      - name: Cache dependencies and build artifacts
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.npm
+            ${{ github.workspace }}/${{ matrix.project }}/.next/cache
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
+
+      - name: Install dependencies
+        working-directory: ./${{ matrix.project }}
+        run: npm i
+
       - name: Build project
         continue-on-error: true
         id: build
@@ -164,7 +164,7 @@ jobs:
           else
             export DOTENV_KEY=${{ secrets.PAYZONE_DOTENV_KEY }}
           fi
-          npm run build:ci || (echo "Failed to build ${{ matrix.project }}" && core.setFailed(`Failed to build ${project}`) && exit 1)
+          npm run build:ci || { core.setFailed(`Failed to build ${project}`); echo "Failed to build ${{ matrix.project }}"; exit 1; }
 
       - name: Update Build Status in Comments
         continue-on-error: true
