refactor: improved error handling and cache management

diff --git a/.github/workflows/preview-deploy.yml b/.github/workflows/preview-deploy.yml
--- a/.github/workflows/preview-deploy.yml
+++ b/.github/workflows/preview-deploy.yml
@@ -125,10 +125,6 @@ jobs:
         with:
           node-version: "20"
 
-      - name: Setup build environment
-        run: |
-          mkdir -p ./${{ matrix.project }}
-
       - name: Cache dependencies and build artifacts
         uses: actions/cache@v4
         with:
@@ -136,6 +132,7 @@ jobs:
             ~/.npm
             .next/cache
             ${{ github.workspace }}/.next/cache
+            ${{ github.workspace }}/${{ matrix.project }}/.next/cache
             node_modules
             ~/${{ matrix.project }}
           key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
@@ -144,23 +141,31 @@ jobs:
 
       - name: Install dependencies
         continue-on-error: true
+        id: install
         working-directory: ./${{ matrix.project }}
         run: |
           if ! npm i; then
+            echo "install-status=0" >> $GITHUB_OUTPUT
             exit 1
           fi
 
       - name: Build project
-        if: success()
         continue-on-error: true
         id: build
         working-directory: ./${{ matrix.project }}
         run: |
+          if [${{steps.install.outputs.install-status == 0}} ]; then
+            echo "npm install failed"
+            echo "build-status=0" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+
           if [ "${{ matrix.project }}" = "portal" ]; then
             export DOTENV_KEY=${{ secrets.PORTAL_DOTENV_KEY }}
           else
             export DOTENV_KEY=${{ secrets.PAYZONE_DOTENV_KEY }}
           fi
+
           if ! npm run build:ci; then
             echo "build-status=0" >> $GITHUB_OUTPUT
             exit 1
@@ -184,13 +189,17 @@ jobs:
             // Handle labels
             const labelsToRemove = [`building-${project}`, `${project}-build-failed`, `${project}-preview-deployed`];
             for (const label of labelsToRemove) {
+              try{
                 await github.rest.issues.removeLabel({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   issue_number: context.issue.number,
                   name: label
                 });
+              } catch (e) {
+                  console.error(`Failed to remove label: ${label}`, e.message);
               }
+            }
             // Add appropriate label based on build status
             const newLabel = buildFailed ? `${project}-build-failed` : `${project}-preview-deployed`;
             await github.rest.issues.addLabels({
@@ -239,7 +248,7 @@ jobs:
 
       - name: Upload using rsync
         continue-on-error: true
-        if: success()
+        if: ${{steps.build.outputs.build-status == 1 }}
         uses: burnett01/rsync-deployments@7.0.1
         with:
           switches: "-av --delete --partial --bwlimit=5000"
@@ -250,7 +259,7 @@ jobs:
           remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
       - name: Set up SSH (secured)
-        if: success()
+        if: ${{steps.build.outputs.build-status == 1 }}
         uses: webfactory/ssh-agent@v0.9.0
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
@@ -258,7 +267,7 @@ jobs:
 
       - name: Deploy on DigitalOcean
         continue-on-error: true
-        if: success()
+        if: ${{steps.build.outputs.build-status == 1 }}
         id: deploy
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'ENDSSH'
@@ -267,26 +276,17 @@ jobs:
             # Set variables
             PROJECT="${{ matrix.project }}"
             PR_NUMBER="${{ github.event.pull_request.number }}"
-            PORT="${{ steps.calculate-port.outputs.port }}"
             APP_PATH="/home/${{ secrets.DROPLET_USER }}/apps/builds/${PROJECT}/preview/${PR_NUMBER}"
             # Navigate to the deployment path
             cd "$APP_PATH"
             
-            # Copy environment file if it exists
-            # if [ -f /home/${{ secrets.DROPLET_USER }}/apps/moon-portal-app/${PROJECT}/.env.preview ]; then
-            #   cp /home/${{ secrets.DROPLET_USER }}/apps/moon-portal-app/${PROJECT}/.env.preview .env
-            #   echo "PORT=${PORT}" >> .env
-            #   chmod 600 .env  # Secure permissions for env file
-            # else
-            #   echo "Warning: .env.preview file not found"
-            #   exit 1
-            # fi
+            if [ "${{ matrix.project }}" = "portal" ]; then
+              export DOTENV_KEY=${{ secrets.PORTAL_DOTENV_KEY }}
+            else
+              export DOTENV_KEY=${{ secrets.PAYZONE_DOTENV_KEY }}
+            fi
 
-            # if [ "${{ matrix.project }}" = "portal" ]; then
-            #   export DOTENV_KEY=${{ secrets.PORTAL_DOTENV_KEY }}
-            # else
-            #   export DOTENV_KEY=${{ secrets.PAYZONE_DOTENV_KEY }}
-            # fi
+            export PORT=${{ steps.calculate-port.outputs.port }}
 
             # npm install dotenv --save
 
@@ -305,7 +305,7 @@ jobs:
           ENDSSH
 
       - name: Update comment with preview URL
-        if: success()
+        if: ${{steps.build.outputs.build-status == 1 }}
         uses: actions/github-script@v6
         with:
           script: |
